- name: demo in template
  hosts: localhost
  tasks:
    - name: copy example.cof
      ansible.builtin.copy:
        src: example.conf
        dest: /tmp/example-copy.conf

    - name: template example.cof
      ansible.builtin.template:
        src: example.conf
        dest: /tmp/example-template.conf
