- name: loop demo
  hosts: localhost
  tasks:
    - name: print fruits
      ansible.builtin.debug:
        msg: "fruits name - {{ item }}"
        loop:
          - apple
          - banana
          - orange

